### ISSUE TITLE
Implement ESLint's no-unused-vars

### ISSUE THREAD

**Issue by EmilyRosina** [SoftwareEngineeringDaily/sedaily-front-end#483]
### declared but unused vars...
- could potentially cause bugs
- lengthen the code unnecessarily
- can lead to confusion by other devs
- increase tech debt the longer we don't have this in place

### Tasks
- [ ] add rule to config `eslintrc.js`
- [ ] remove all unused vars throughout project
- [ ] run through [test list](https://github.com/SoftwareEngineeringDaily/sedaily-front-end/blob/develop/ManualTestingChecklist.md), to make sure nothing broke

---
[**ESLint** docs for **no-unused-vars**](https://eslint.org/docs/rules/no-unused-vars)

💭 💬 @jasonify @dfcook @TheHollidayInn @joshmorel @crablar @tyler-furby
